services:
    pgsql:
        image: 'postgres:15'
        ports:
            - "5432:5432"
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
        networks:
            - app

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    pgsql:
    redis:
